# Generated by Django 4.1.5 on 2023-02-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project", old_name="amount", new_name="budget_amount",
        ),
        migrations.RenameField(
            model_name="project", old_name="location", new_name="contract_title",
        ),
        migrations.RenameField(
            model_name="project", old_name="status", new_name="lga",
        ),
        migrations.AddField(
            model_name="project",
            name="contract_amount",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="mda",
            field=models.CharField(default=20, max_length=255),
            preserve_default=False,
        ),
    ]
